### ISSUE TITLE
"OverflowError: string longer than 2147483647 bytes" while trying to upload ~6G CSV file

### ISSUE THREAD

**Issue by mbeilin** [datopian/ckan3-py-sdk#23]
While trying to upload ~6G CSV file via `ckanclient.Client.push_blob` getting the following error:
```
Traceback (most recent call last):
  File "/home/michael/PycharmProjects/nhs_upload_test/venv/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/michael/PycharmProjects/nhs_upload_test/venv/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/michael/PycharmProjects/nhs_upload_test/venv/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/michael/PycharmProjects/nhs_upload_test/venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/michael/PycharmProjects/nhs_upload_test/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/michael/PycharmProjects/nhs_upload_test/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1081, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 1002, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes
```
## Analysis

See this issue in `requests` repo - https://github.com/psf/requests/issues/2717
As per this the possible workaround should be:
```
datafile = 'someHugeFile'
with open(datafile, 'rb') as myfile:
    resp = requests.put(url, data=myfile, verify=False)
```

**Comment by rufuspollock** [comment]
@cuducos are we loading the whole file into memory? We want to avoid doing that but instead streaming it ... (is that possible with requests ...)

**Comment by rufuspollock** [comment]
@mbeilin i don't think that is a workaround reading the thread. I think the best answer seems to be in further down comments e.g. https://github.com/psf/requests/issues/2717#issuecomment-724725392

**Comment by cuducos** [comment]
@rufuspollock, yep, in fact [we are](https://github.com/datopian/ckan-client-py/blob/master/ckanclient/upload.py#L16) — the `.read_bytes()` does that. That's a great point for improvement indeed.

**Comment by rufuspollock** [comment]
@cuducos can you look at a fix for the issue @mbeilin has reported then? It seems you may need `requests-toolbelt` (?)

**Comment by Daniellappv** [comment]
@shevron hey, can you maybe take a quick look at the fix for the issue @mbeilin has reported? 
<img width="489" alt="Screenshot 2020-12-14 at 15 41 24" src="https://user-images.githubusercontent.com/45828069/102087892-d6e3de00-3e22-11eb-815b-fa553c3423b8.png">
**For context:** 
The main objective is to get a fully reproducible python script/bit of code using the API that would show how to: 
1) create a dataset and add a resource (CSV) 
2) update/ add a new resource to an existing dataset

**Comment by shevron** [comment]
Most likely, we need to implement #25 . Doing this will probably resolve this issue as well as #24.
